version: "3.8"

services:
  db:
    image: postgres:15
    container_name: recipes-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: recipes-api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
