version: "3.8"

services:
  db:
    image: postgres:15
    container_name: recipes-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - recipes-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: recipes-app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  recipes-data:
